### ISSUE TITLE
Heroku App Crash

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#49]
Around 2:09am on Feb15th the app crashed on Heroku sending me over 20 e-mails. Support has been alerted on Heroku and currently investigating the issues.

**Comment by grayghostvisuals** [comment]
```
In context:
2015-02-15 07:08:53.858 126 <190>1 2015-02-15T07:08:53.681577+00:00 app web.1 - -                                ^
2015-02-15 07:08:53.858 150 <190>1 2015-02-15T07:08:53.684935+00:00 app web.1 - - TypeError: Cannot read property '_contents' of undefined
    at process (/app/builder.js:142:32)
    at /app/builder.js:195:9
    at /app/builder.js:99:13
    at DestroyableTransform.end [as _flush] (/app/node_modules/gulp-util/lib/buffer.js:8:12)
    at DestroyableTransform.<anonymous> (/app/node_modules/gulp-util/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:180:16)
2015-02-15 07:08:53.914 293 <158>1 2015-02-15T07:08:53.539740+00:00 heroku router - - at=info method=GET path="/css/style.css" host=www.transformicons.com request_id=eba5f89f-b619-4aa0-8ce6-6244237bc512 fwd="46.195.205.114" dyno=web.1 connect=1ms service=6ms status=200 bytes=19387
2015-02-15 07:08:53.918 113 <190>1 2015-02-15T07:08:53.681263+00:00 app web.1 - - /app/builder.js:142
2015-02-15 07:08:53.925 144 <190>1 2015-02-15T07:08:53.684950+00:00 app web.1 - -     at DestroyableTransform.emit (events.js:92:17)
2015-02-15 07:08:53.925 224 <190>1 2015-02-15T07:08:53.684952+00:00 app web.1 - -     at finishMaybe (/app/node_modules/gulp-util/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
2015-02-15 07:08:53.925 223 <190>1 2015-02-15T07:08:53.684953+00:00 app web.1 - -     at endWritable (/app/node_modules/gulp-util/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
2015-02-15 07:08:53.925 245 <190>1 2015-02-15T07:08:53.684955+00:00 app web.1 - -     at DestroyableTransform.Writable.end (/app/node_modules/gulp-util/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
2015-02-15 07:08:54.858 124 <45>1 2015-02-15T07:08:54.486315+00:00 heroku web.1 - - Process exited with status 8
2015-02-15 07:08:55.116 128 <45>1 2015-02-15T07:08:54.493665+00:00 heroku web.1 - - State changed from up to crashed
2015-02-15 07:08:59.443 301 <158>1 2015-02-15T07:08:59.159142+00:00 heroku router - - at=error code=H10 desc="App crashed" method=GET path="/" host=www.transformicons.com request_id=65b74944-5415-4fdd-85e0-84bf87e39cab fwd="98.192.1.75" dyno=web.1 connect=5002ms service= status=503 bytes=
```

**Comment by grayghostvisuals** [comment]
@jfroffice This is actually what is occurring in the logs right now. The deps.json appears to have the correct references :\

**Comment by jfroffice** [comment]
@grayghostvisuals I reproduce the bug while playing with email--envelope or vid--play transform.

I saw little improvement to avoid this bug.

**Comment by grayghostvisuals** [comment]
> I saw little improvement to avoid this bug.

What does that mean?

**Comment by jfroffice** [comment]
I pull the code it will be more simple.

**Comment by jfroffice** [comment]
There might be a problem of consistency between the CSS class naming, SCSS file naming, and keys define in deps.json.

If there is an inconsistency the app might crash.

This patch try to avoid the crash.
